feat:finish react render logic
eggjs/egg-view-react pull request #1
Opened 2017-01-24 08:05 UTC by jtyjty99999

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2017-02-04 07:46 UTC, atian25 requested changes

2017-02-04 07:46 UTC, atian25 commented on config/config.default.js
> +  exports['view-react'] = {
`view-react` -> `view`

2017-02-04 07:46 UTC, atian25 commented on config/config.default.js
> +    loadpath: path.join(appInfo.baseDir, 'app/view'),
`loadpath` -> `dir`, 参见 https://eggjs.org/zh-cn/advanced/view-plugin.html

2017-02-04 07:46 UTC, atian25 commented on config/config.default.js
> +  const exports = {};
exports 改为 config 吧

2017-02-04 07:46 UTC, atian25 commented on lib/view.js
> +    this._config = ctx.app.config['view-react'];
不用下划线.

`this.config = ctx.app.config.view;`

2017-02-04 07:46 UTC, atian25 commented on lib/view.js
> +    const extname = this._config.extname.replace(/^\.?/, '.');
这边预处理是不是可以放到上面, 不用每次 render 都做

2017-02-04 07:46 UTC, atian25 commented on lib/view.js
> +      resolve(html);
直接放到 try 里面?

2017-02-04 07:46 UTC, atian25 commented on lib/view_helper.js
> +  // 仅用于 View, 避免污染 Helper
中文注释

2017-02-04 07:46 UTC, atian25 commented on test/fixtures/apps/view-react-test/app/controller/test.js
> +/**
干掉

2017-02-04 07:46 UTC, atian25 commented on test/fixtures/apps/view-react-test/app/router.js
> +  app.get('/', app.controller.test);
`app.get('/', 'test');`

2017-02-04 07:46 UTC, atian25 commented on test/view-react.test.js
> +  it('should render', done => {
为何改为 done 方式?

2017-02-04 07:46 UTC, atian25 commented on package.json
>      "egg": "^0.7.0",
0.7.0 太低了

2017-02-04 08:34 UTC, jtyjty99999 commented on lib/view.js
> +      resolve(html);
这样逻辑上看着正常些，先处理没出错再resolve，而不是resolve时出错的感觉

2017-02-04 08:36 UTC, jtyjty99999 commented
@atian25 都修改了

2017-02-04 09:20 UTC, jtyjty99999 commented
这个组件ok了以后，就可以写egg同构的例子了

2017-02-04 09:52 UTC, atian25 commented on package.json
> +    "egg": "~0.8.0",
为什么用 `~0.8.0` 而不是 `^0.10.0`?

2017-02-04 09:52 UTC, atian25 commented on config/config.default.js
> +    cache: true,
config.local.js 需要配置 cache: false 么?

话说 react 服务端渲染, 开发期是怎么处理缓存还有 require 的?

2017-02-04 09:52 UTC, atian25 commented on lib/view.js
> +    const reactFile = path.join(this.config.dir, name + this.extname);
@popomore 也看看? 对同构渲染这块的整个工作流不太了解, 之前好像看到 vue 那边是构建为几个 bundle 的?

2017-02-04 12:48 UTC, popomore commented on package.json
> +    "egg": "~0.8.0",
用 autod 更新下吧

2017-02-06 05:43 UTC, jtyjty99999 commented on config/config.default.js
> +    cache: true,
没缓存，很难做缓存，因为数据是会变的，如果缓存的话，命中率很低，内存会爆

2017-02-06 05:43 UTC, atian25 commented on config/config.default.js
> +    cache: true,
没有缓存那这里还要 cache: true ?

2017-02-06 05:44 UTC, jtyjty99999 commented on lib/view.js
> +    const reactFile = path.join(this.config.dir, name + this.extname);
其实就是把react当模板引擎，配合数据来渲染jsx文件，只不过jsx里有逻辑，而且这一步还没到同构，同构的话需要浏览器也渲染一遍

2017-02-06 07:10 UTC, popomore commented on lib/view.js
> +    const reactFile = path.join(this.config.dir, name + this.extname);
我们现在没用 react 的 RSS，也不知道哪种方式好

2017-02-06 07:13 UTC, popomore commented on lib/view.js
> +        this.ctx.coreLogger.error('fail to render react component %s', reactFile);
这个不用打吧，抛给 onerror 处理

2017-02-06 07:13 UTC, popomore commented on lib/view.js
> +        html += this.app.viewEngine.renderToString(React.createElement(reactComponent.default || reactComponent, locals || {}));
这里不用 `+=`  吧

2017-02-06 07:14 UTC, popomore commented on lib/view.js
> +  get helper() {
这个 helper 好像没用？

2017-02-06 10:47 UTC, jtyjty99999 commented on lib/view.js
> +        html += this.app.viewEngine.renderToString(React.createElement(reactComponent.default || reactComponent, locals || {}));
这个地方后面考虑会有一些拼接，因为不可能在react组件里写doctype，所以这里可能会提供一个默认的doctype

2017-02-07 02:50 UTC, fengmk2 commented on test/fixtures/apps/view-react-test/app/view/test.js
> +'use strict';
这是 jsx 文件后缀吧

2017-02-07 02:51 UTC, fengmk2 commented on test/view-react.test.js
> +const htmlRendered = '<div data-reactroot="" data-reactid="1" data-react-checksum="1355557741"><!-- react-text: 2 -->hello <!-- /react-text --><!-- react-text: 3 -->world<!-- /react-text --></div>';
`<!-- react-text: 2 -->` 注释一定要在吗？

2017-02-07 02:54 UTC, jtyjty99999 commented on test/fixtures/apps/view-react-test/app/view/test.js
> +'use strict';
可以配置的，支持jsx js

2017-02-07 04:07 UTC, atian25 commented on lib/view.js
> +  get helper() {
按他这里是没用上

2017-02-07 05:52 UTC, popomore commented on lib/view.js
> +  get helper() {
这个没改？

2017-02-07 05:53 UTC, popomore commented on lib/view.js
> +        html += this.app.viewEngine.renderToString(React.createElement(reactComponent.default || reactComponent, locals || {}));
那加上呗

2017-02-07 06:32 UTC, jtyjty99999 commented
@popomore fixed

2017-02-07 07:47 UTC, atian25 commented
cc @dfguo

2017-02-08 02:19 UTC, jtyjty99999 commented
@atian25 可以合了吧

2017-02-08 02:19 UTC, atian25 approved these changes

2017-02-08 02:22 UTC, atian25 reviewed
+1

2017-02-08 02:22 UTC, atian25 commented on lib/view_helper.js
> +      return this.safe(super.shtml(str));
这个在 react 里面能用么? safe 的方式好像不一样吧? 加个用例看看?

2017-02-08 02:22 UTC, atian25 commented on package.json
> +    "cheerio": "~0.20.0",
有用到么?

2017-02-08 02:52 UTC, jtyjty99999 commented
@atian25 我想错了，去掉了原有helper的支持

2017-02-08 02:55 UTC, atian25 commented on package.json
> +    "egg": "~0.8.0",
@jtyjty99999 用 autod 更新下 egg 的版本, 现在是 0.11.0 了.

其他 +1

2017-02-08 07:56 UTC, jtyjty99999 commented
@atian25 done

2017-02-08 07:57 UTC, atian25 commented on package.json
> +    "egg": "~0.8.0",
我这边看到这里还是 "~0.8.0"

2017-02-08 07:58 UTC, atian25 commented
@jtyjty99999 egg 的版本还是没改

2017-02-08 08:00 UTC, jtyjty99999 commented
@atian25 done

2017-02-08 08:12 UTC, atian25 approved these changes

2017-02-08 08:13 UTC, atian25 commented
+1

2017-02-08 09:00 UTC, merged

2017-07-17 08:24 UTC, chengnuo commented
@jtyjty99999 这个是可以用了吗?

2017-08-07 10:25 UTC, hubcarl commented
@chengnuo  react ssr 工程项目参考： https://github.com/hubcarl/egg-react-webpack-boilerplate
egg-view-react 插件在plugin下面， 这周写单元测试，准备发1.0PR